backend:
  name: github
  repo: Summit-DevLabs/motion-hive
  branch: develop

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    format: "frontmatter"
    extension: "mdx"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" } 